---
# tasks file for configure_rhel_subscription
- name: install apache2
  include: rhel_subscription.yml
  when: ansible_facts['distribution'] == 'RedHat' and ansible_facts['distribution_major_version'] == "8"
