---
# tasks file for configure_rhel_subscription

#subscription-manager] To install it use: ansible-galaxy collection install community.general
#Katello] ansible-galaxy collection install theforeman.foreman

#To use it in a playbook, specify: community.general.redhat_subscription

#copy ak-katello-ca-consumer-latest.noarch.rpm over
- name: copy katello akl file over
  copy:
    src: akl-katello-ca-consumer-latest.noarch.rpm
    dest: /tmp/katello-ca-consumer-latest.noarch.rpm
    owner: root
    group: root
    mode: '0444'
  when: vcenter_datacenter|lower == "khyber pass vi" or
        vcenter_datacenter|lower == "khyberpassvi" or
        vcenter_datacenter|lower == "khyber pass nfv" or
        vcenter_datacenter|lower == "khyberpassnfv"

- name: copy katello hlz file over
  copy:
    src: hlz-katello-ca-consumer-latest.noarch.rpm
    dest: /tmp/katello-ca-consumer-latest.noarch.rpm
    owner: root
    group: root
    mode: '0444'
  when: vcenter_datacenter|lower == "hamilton vi" or
        vcenter_datacenter|lower == "hamiltonvi" or
        vcenter_datacenter|lower == "hamilton nfv" or
        vcenter_datacenter|lower == "hamiltonnfv"

- name: isntall katello file
  yum:
   name: /tmp/katello-ca-consumer-latest.noarch.rpm
   disable_gpg_check: yes
   state: present
  vars:
    ansible_python_interpreter: /usr/bin/python2

#disable spacewalk
- name: copy over the spacewalk conf
  copy:
    src: spacewalk.conf
    dest: /etc/dnf/plugins/spacewalk.conf
    owner: root
    group: root
    mode: '0644'

- name: move rhclassic systemid
  ansible.builtin.command: mv /etc/sysconfig/rhn/systemid /root/systemid.old
  ignore_errors: yes

#subscription-manager register --org="Default_Organization" --activationkey="RHEL7_Key"
- name: register the server
  community.general.redhat_subscription:
    state: present
    activationkey: RHEL7_Key
#    auto_attach: yes
    org_id: Default_Organization
    force_register: yes
  when: ansible_facts['distribution'] == 'RedHat' and ansible_facts['distribution_major_version'] == "7"

- name : Enable all repos
  ansible.builtin.command: 'subscription-manager repos --enable=*'
  when: ansible_facts['distribution'] == 'RedHat' and ansible_facts['distribution_major_version'] == "7"

#- name: Enable all repositories
#  community.general.rhsm_repository:
#    name: 'rhel-7-*'
#    state: enabled
#  when: ansible_distribution == "RedHat" and ansible_distribution_major_version == "7"

- name: refresh yum
  ansible.builtin.command: yum clean all
  when: ansible_facts['distribution'] == 'RedHat' and ansible_facts['distribution_major_version'] == "7"

- name: install katello packages
  yum:
    name:
      - katello-host-tools
      - katello-agent
    state: latest
  vars:
    ansible_python_interpreter: /usr/bin/python2
  when: ansible_facts['distribution'] == 'RedHat' and ansible_facts['distribution_major_version'] == "7"

#- name: yum update the system
#  yum:
#    name:  "*"
#    state: latest
#    exclude: openssh,openssh-server,openssh-clients
#  vars:
#    ansible_python_interpreter: /usr/bin/python2
#  when: ansible_facts['distribution'] == 'RedHat' and ansible_facts  ['distribution_major_version'] >= '7'

#- name: Pause for 20 seconds to make sure ssh is running
#  pause:
#    seconds: 20
