---
# tasks file for configure_bgaccounts
- name: make sure pwgen is installed on redhat and centos
  dnf:
    name:
    - pwgen
    state: present
  when: ansible_facts['distribution'] == 'RedHat' and ansible_distribution_version >= '8'

- name: make sure pwgen is installed on ubuntu
  apt:
    name:
    - pwgen
    state: present
  when: ansible_facts['distribution'] == 'Ubuntu'

- name: install bg accoutn password set script
  copy:
    src: set-bg-passwords.pl
    dest: /usr/local/sbin/set-bg-passwords.pl
    owner: root
    group: root
    mode: '0700'
  when: (ansible_facts['distribution'] == "Ubuntu") or
        (ansible_facts['distribution'] == 'RedHat' and ansible_distribution_version >= '8')

- name: Change root password
  user:
    name: root
    update_password: always
    password: "{{ vm_root_password|password_hash('sha512') }}"
  when: (ansible_facts['distribution'] == "Ubuntu") or
        (ansible_facts['distribution'] == 'RedHat' and ansible_distribution_version >= '8')

- name: Change zeus password
  user:
    name: zeus
    update_password: always
    password: "{{ vm_zeus_password|password_hash('sha512') }}"
  when: (ansible_facts['distribution'] == "Ubuntu") or
        (ansible_facts['distribution'] == 'RedHat' and ansible_distribution_version >= '8')

- name: Change root password redhat 7 and below
  user:
    name: root
    update_password: always
    password: "{{ vm_root_password|password_hash('sha512') }}"
  vars:
    ansible_python_interpreter: /usr/bin/python2
  when: ansible_facts['distribution'] == 'RedHat' and ansible_distribution_version < '8'

- name: Change zeus password redhat 7 and below
  user:
    name: zeus
    update_password: always
    password: "{{ vm_zeus_password|password_hash('sha512') }}"
  vars:
    ansible_python_interpreter: /usr/bin/python2
  when: ansible_facts['distribution'] == 'RedHat' and ansible_distribution_version < '8'
