---
# tasks file for configure_upguardaccess

- name: copy the firewall rule to the server
  ansible.builtin.copy:
    src: firewall-rules-available/ans_ssh-jumphost.v4
    dest: /etc/fw-2d/rules-available/ans_ssh-jumphost.v4
    owner: root
    group: root
    mode: '0400'

- name: Enable firewall rule
  file:
    src: /etc/fw-2d/rules-available/ans_ssh-jumphost.v4
    dest: /etc/fw-2d/rules-enabled/33_ans_ssh-jumphost.v4
    owner: root
    group: root
    state: link

- name: enable the firewall
  shell: /usr/local/sbin/firewall-up



- name: copy the ssh match rule to the server
  ansible.builtin.copy:
    src: ssh-matches-available/ans_ssh-bastion-acs.group
    dest: /etc/ssh/matches-available/ans_ssh-bastion-acs.group
    owner: root
    group: root
    mode: '0400'

- name: copy the fixed-appops ssh match rule to the server
  ansible.builtin.copy:
    src: ssh-matches-available/ans_ssh-bastion-fixed-appops.group
    dest: /etc/ssh/matches-available/ans_ssh-bastion-fixed-appops.group
    owner: root
    group: root
    mode: '0400'

- name: copy the contractor ssh match rule to the server
  ansible.builtin.copy:
    src: ssh-matches-available/ans_ssh-bastion-contractor.group
    dest: /etc/ssh/matches-available/ans_ssh-bastion-contractor.group
    owner: root
    group: root
    mode: '0400'

- name: copy the ssh match rule to the server
  ansible.builtin.copy:
    src: ssh-matches-available/ans_ssh-bastion-dbops.group
    dest: /etc/ssh/matches-available/ans_ssh-bastion-dbops.group
    owner: root
    group: root
    mode: '0400'

- name: copy the fixed-appdevs ssh match rule to the server
  ansible.builtin.copy:
    src: ssh-matches-available/ans_ssh-bastion-fixed-appdevs.group
    dest: /etc/ssh/matches-available/ans_ssh-bastion-fixed-appdevs.group
    owner: root
    group: root
    mode: '0400'

- name: copy the fixed-appops ssh match rule to the server
  ansible.builtin.copy:
    src: ssh-matches-available/ans_ssh-bastion-fixed-appops.group
    dest: /etc/ssh/matches-available/ans_ssh-bastion-fixed-appops.group
    owner: root
    group: root
    mode: '0400'

- name: copy the ia-network-jump ssh match rule to the server
  ansible.builtin.copy:
    src: ssh-matches-available/ans_ssh-bastion-ia-network-jump.group
    dest: /etc/ssh/matches-available/ans_ssh-bastion-ia-network-jump.group
    owner: root
    group: root
    mode: '0400'

- name: copy the ia-sysadmin-jump ssh match rule to the server
  ansible.builtin.copy:
    src: ssh-matches-available/ans_ssh-bastion-ia-sysadmin-jump.group
    dest: /etc/ssh/matches-available/ans_ssh-bastion-ia-sysadmin-jump.group
    owner: root
    group: root
    mode: '0400'

- name: copy the sysadmin ssh match rule to the server
  ansible.builtin.copy:
    src: ssh-matches-available/ans_ssh-bastion-sysadmin.group
    dest: /etc/ssh/matches-available/ans_ssh-bastion-sysadmin.group
    owner: root
    group: root
    mode: '0400'

- name: copy the techm-db ssh match rule to the server
  ansible.builtin.copy:
    src: ssh-matches-available/ans_ssh-bastion-techm-db.group
    dest: /etc/ssh/matches-available/ans_ssh-bastion-techm-db.group
    owner: root
    group: root
    mode: '0400'

- name: copy the techm-ops ssh match rule to the server
  ansible.builtin.copy:
    src: ssh-matches-available/ans_ssh-bastion-techm-ops.group
    dest: /etc/ssh/matches-available/ans_ssh-bastion-techm-ops.group
    owner: root
    group: root
    mode: '0400'

- name: copy the splunkforwarder-jump ssh match rule to the server
  ansible.builtin.copy:
    src: ssh-matches-available/ans_ssh-bastion-splunkforwarder-jump.group
    dest: /etc/ssh/matches-available/ans_ssh-bastion-splunkforwarder-jump.group
    owner: root
    group: root
    mode: '0400'

- name: Enable sysadmin-jumpssh match rule
  file:
    src: /etc/ssh/matches-available/ans_ssh-bastion-ia-sysadmin-jump.group
    dest: /etc/ssh/matches-enabled/10_ans_ssh-bastion-ia-sysadmin-jump.group
    owner: root
    group: root
    state: link

- name: Enable sysadmin match rule
  file:
    src: /etc/ssh/matches-available/ans_ssh-bastion-sysadmin.group
    dest: /etc/ssh/matches-enabled/10_ans_ssh-bastion-sysadmin.group
    owner: root
    group: root
    state: link

- name: Enable techm ssh match rule
  file:
    src: /etc/ssh/matches-available/ans_ssh-bastion-techm-ops.group
    dest: /etc/ssh/matches-enabled/10_ans_ssh-bastion-techm-ops.group
    owner: root
    group: root
    state: link

- name: apply the ssh eabled rules
  shell: /usr/local/sbin/apply_ssh.sh
