#!/bin/bash
IPTABLES="`which iptables`"
IP6TABLES="`which ip6tables`"

#########
###ip4###
#########
# Setup Default Policies
$IPTABLES -P INPUT ACCEPT
$IPTABLES -P FORWARD ACCEPT
$IPTABLES -P OUTPUT ACCEPT

# Flush Chains
$IPTABLES -F
$IPTABLES -t nat -F

# Delete Non-System Chains
$IPTABLES -X

#########
###ip6###
#########
# Setup Default Policies
$IP6TABLES -P INPUT ACCEPT
$IP6TABLES -P FORWARD ACCEPT
$IP6TABLES -P OUTPUT ACCEPT

# Flush Chains
$IP6TABLES -F
$IP6TABLES -t nat -F

# Delete Non-System Chains
$IP6TABLES -X
