---
# tasks file for harden_docker

- name: Add the docker-ce repo key
  apt_key:
    url: https://repo.snap.net.nz/docker-ce/key.gpg
    state: present
  when: ansible_facts['distribution'] == 'Ubuntu'

- name: Add docker-ce repo for ubuntu 16
  apt_repository:
    repo: deb [arch=amd64] http://repo.snap.net.nz/docker-ce/linux/ubuntu xenial stable
    state: present
    filename: docker-ce
  when:
    - ansible_facts['distribution'] == 'Ubuntu'
    - ansible_facts['distribution_major_version'] == '16'

- name: Add docker-ce repo for ubuntu 18
  apt_repository:
    repo: deb [arch=amd64] http://repo.snap.net.nz/docker-ce/linux/ubuntu bionic stable
    state: present
    filename: docker-ce
  when:
    - ansible_facts['distribution'] == 'Ubuntu'
    - ansible_facts['distribution_major_version'] == '18'

#- name: install centos 2d-firewall
#  include: ce_extractdeb.yml
#  ignore_errors: yes
#  when: ansible_facts['distribution'] == 'CentOS' or ansible_facts['distribution'] == 'RedHat'

#- name: start firewall centos
#  include: ce_start_firewall.yml
#  ignore_errors: yes
#  when: ansible_facts['distribution'] == 'CentOS' or ansible_facts['distribution'] == 'RedHat'

- name: copy auditd rules
  copy:
   src: 60_docker.rules
   dest: /etc/audit/rules.d/60_docker.rules
   owner: root
   group: root
   mode: '0640'



- name: enable audit rules
  shell: /usr/sbin/augenrules --load
  notify:
#  - restart auditd centos7 # we don't restart because we should reboot manually
#  - restart auditd centos8
  - restart rsyslog
  when: ansible_facts['distribution'] == 'CentOS' or ansible_facts['distribution'] == 'RedHat'

- name: enable audit rules
  shell: /sbin/augenrules --load
  notify:
#  - restart auditd ubuntu# we don't restart because we should reboot manually
  - restart rsyslog
  when: ansible_facts['distribution'] == 'Ubuntu'
