---
# tasks file for configure_hostcerts
- name: Copy ssh_host_ed25519_key-cert
  copy:
    src: ../../files/{{inventory_hostname}}ssh_host_ed25519_key-cert.pub
    dest: /etc/ssh/ssh_host_ed25519_key-cert.pub
    owner: root
    group: root
    mode: '0644'

- name: Copy ssh_host_ed25519_key
  copy:
    src: ../../files/{{inventory_hostname}}ssh_host_ed25519_key
    dest: /etc/ssh/ssh_host_ed25519_key
    owner: root
    group: root
    mode: '0600'
