#https://docs.ansible.com/ansible/latest/modules/copy_module.html
- name: Deploy snap.net.nz.pem cert
  copy:
    src: snap.net.nz.pem
    dest: /etc/ssl/private/snap.net.nz.pem
    owner: root
    group: ssl-cert
    mode: '640'
