---
# tasks file for configure_upguardaccess

- name: install ipaclient tools
  ansible.builtin.dnf:
    name:
      - oddjob-mkhomedir
      - oddjob
      - freeipa-client
      - ipa-admintools
      - sssd-tools
      - sssd
    state: latest
    update_cache: yes
  when: (ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_major_version'] == "8")

- name: ipaclientinstall join
  ansible.builtin.command:
    argv:
      - /usr/sbin/ipa-client-install
      - --domain
      - "{{ ipadomain }}"
      - --realm
      - "{{ iparealm }}"
      - --mkhomedir
      - --enable-dns-updates
      - --unattended
      - --force-join
      - --principal
      - "{{ ipaprincipal }}"
      - --ntp-server
      - ipa-master-stag.2dtest.nz
      - --ssh-trust-dns
      - -W
    stdin: "{{ ipapassword }}"
  # you don't want to show passwords in your logs
 #no_log: true
