---
# tasks file for postinstall_cleanup
#reboot the server so hardening takes affect
- name: Unconditionally reboot the machine waiting for 120 seconds - 2mins before testing connection again
  reboot:
    reboot_timeout: 120



#remove the .authorized_keys file for zeus so people can't ssh in without a password
#- name: Remove file /home/zeus/.ssh/authorized_keys
#  file:
#    path: /home/zeus/.ssh/authorized_keys
#    state: absent

#command to remove authorized.keys files and to remove matches file?

#- name: remove zeus pubkey auth
#  replace:
#    path: /etc/ssh/sshd_config.d/matches
#    regexp: '^Match User zeus\n.*Auth.*$'
#    replace: ''

#- name: remove zeus sudoers file
#  file:
#   path: /etc/sudoers.d/deploy_zeus
#   state: absent

#
#FINAL TASK
#nothing should be placced after this task as anything placed after this will not work
#removing the sudoers file must be the last thing else you can't run any sudo commands after the file is removed
#
- name: zeus sudoers file and authorization_keys file
  ansible.builtin.command: "{{ item }}"
  with_items:
    - rm /home/zeus/.ssh/authorized_keys
    - "ln -s /etc/ssh/matches-available/ans_zeus.user /etc/ssh/matches-enabled/05_ans_zeus.user"
    - /usr/local/sbin/apply_ssh.sh
    - rm /etc/sudoers.d/deploy_zeus
