- name: RH link version for motd
  file:
    src: /etc/redhat-release
    dest: /etc/motd.d/10_redhat_release
    state: link
  ignore_errors: yes
  when: ansible_facts['distribution'] == 'RedHat'

- name: remove cockpit motd
  file:
   path: /etc/motd.d/cockpit
   state: absent

- name: RH motd.2d
  copy:
    src: motd.2d
    dest: /etc/motd.d/05_motd.2d
    owner: root
    group: root
    mode: '0644'
  ignore_errors: yes
  when: ansible_facts['distribution'] == 'RedHat'

#- name: UB motd
#  apt:
#    name: 2d-branding
#    state: latest
#    update_cache: yes
#  ignore_errors: yes
#  when: ansible_facts['distribution'] == 'Ubuntu'

- name: UB disable 10-help-text motd
  ansible.builtin.file:
    path: /etc/update-motd.d/10-help-text
    owner: root
    group: root
    mode: '0600'
  when: ansible_facts['distribution'] == 'Ubuntu'
