---
# tasks file for configure_autoreboot
- name: copied 2d autoreboot timer
  ansible.builtin.template:
    src: 2d-autoreboot.timer.j2
    dest: /etc/systemd/system/2d-autoreboot.timer
    owner: root
    group: root
    mode: '0600'

- name: copied 2d_motd_autoreboot
  ansible.builtin.template:
    src: 2d_autoreboot.motd.j2
    dest: /etc/2d_motd_autoreboot
    owner: root
    group: root
    mode: '0755'

#setup motd to display the autoreboot file ######we now ave listtimers in bashrc
#redhat links the file
#- name: RH link /etc/2d_motd_autoreboot to /etc/motd redhat 8 and up
#  file:
#    src: /etc/2d_motd_autoreboot
#    dest: /etc/motd.d/9a_2d_autoreboot
#    state: link
#  ignore_errors: yes
#  when: ansible_facts['distribution'] == 'RedHat' and ansible_distribution_version >= '8'

- name: copied over autoreboot service
  copy:
    src: 2d-autoreboot.service
    dest: /etc/systemd/system/2d-autoreboot.service
    owner: root
    group: root
    mode: '0755'
  ignore_errors: yes

- name: Just force systemd to reread configs (2.4 and above)
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Enabled a timer unit for 2d-autoreboot.timer
  ansible.builtin.systemd:
    name: 2d-autoreboot.timer
    state: started
    enabled: yes
