- name: email from
  lineinfile:
   path: /etc/dnf/automatic.conf
   insertbefore: '[command]'
   regex: '^email_from ='
   line: email_from = root@{{ ansible_hostname }}
  ignore_errors: yes
#  when: (ansible_facts['distribution'] == 'CentOS' and ansible_facts['distribution_major_version'] == "8")

- name: email to
  lineinfile:
   path: /etc/dnf/automatic.conf
   insertbefore: '[command]'
   regex: '^email_to ='
   line: email_to = sysadmin@2degrees.nz
  ignore_errors: yes
#  when: (ansible_facts['distribution'] == 'CentOS' and ansible_facts['distribution_major_version'] == "8")

- name: email host
  lineinfile:
   path: /etc/dnf/automatic.conf
   insertbefore: '[command]'
   regex: '^email_host ='
   line: email_host = smtp@snap.net.nz
  ignore_errors: yes
#  when: (ansible_facts['distribution'] == 'CentOS' and ansible_facts['distribution_major_version'] == "8")

- name: create /etc/systemd/system/dnf-automatic-download.d
  file: 
   path: /etc/systemd/system/dnf-automatic-download.timer.d
   state: directory
   owner: root
   group: root
   mode: 0744

- name: create /etc/systemd/system/dnf-automatic-install.d
  file: 
   path: /etc/systemd/system/dnf-automatic-install.timer.d
   state: directory
   owner: root
   group: root
   mode: 0744

- name: edit download timer
  copy:
   src: dnf-automatic-download.timer.override
   dest: /etc/systemd/system/dnf-automatic-download.timer.d/override.conf
   owner: root
   group: root
   mode: 0644
  ignore_errors: yes
#  when: (ansible_facts['distribution'] == 'CentOS' and ansible_facts['distribution_major_version'] == "8")

- name: edit download timer
  copy:
   src: dnf-automatic-install.timer.override
   dest: /etc/systemd/system/dnf-automatic-install.timer.d/override.conf
   owner: root
   group: root
   mode: 0644
  ignore_errors: yes
#  when: (ansible_facts['distribution'] == 'CentOS' and ansible_facts['distribution_major_version'] == "8")
