- name: RH install dnf-automatic
  ansible.builtin.dnf:
    name:
      - dnf-automatic
      - kpatch-dnf
  ignore_errors: yes
  when: (ansible_facts['distribution'] == 'RedHat')

- name: UB install 2dupgrades
  apt :
    name:
      - 2d-upgrades
  ignore_errors: yes
  when: ansible_facts['distribution'] == 'Ubuntu'
