---
# tasks file for install_autoupdates
- include: install_autoupdates.yml
- include: rh_configure_autoupdates.yml
  when: (ansible_facts['distribution'] == 'RedHat' and ansible_facts['distribution_major_version'] == "8")
- include: rh_enable_autoupdates.yml
  when: (ansible_facts['distribution'] == 'RedHat' and ansible_facts['distribution_major_version'] == "8")
