- name: reload systemctl daemon
  systemd:
    daemon_reload: yes
  ignore_errors: yes
  when: (ansible_facts['distribution'] == 'RedHat' and ansible_facts['distribution_major_version'] == "8")

- name: Enable dnf-automatic-download.service
  service:
    name: dnf-automatic-download.service
    enabled: yes
  ignore_errors: yes
  when: (ansible_facts['distribution'] == 'RedHat' and ansible_facts['distribution_major_version'] == "8")

- name: Enable dnf-automatic-download.timer
  service:
    name: dnf-automatic-download.timer
    enabled: yes
    state: restarted
  ignore_errors: yes
  when: (ansible_facts['distribution'] == 'RedHat' and ansible_facts['distribution_major_version'] == "8")

- name: Enable dnf-automatic-install.service
  service:
    name: dnf-automatic-install.service
    enabled: yes
  ignore_errors: yes
  when: (ansible_facts['distribution'] == 'RedHat' and ansible_facts['distribution_major_version'] == "8")

- name: Enable dnf-automatic-install.timer
  service:
    name: dnf-automatic-install.timer
    enabled: yes
    state: restarted
  ignore_errors: yes
  when: (ansible_facts['distribution'] == 'RedHat' and ansible_facts['distribution_major_version'] == "8")

- name: Enable automatic kernel livepatching
  ansible.builtin.command:
    cmd: yum kpatch auto -y
  when: (ansible_facts['distribution'] == 'RedHat' and ansible_facts['distribution_major_version'] == "8")
