---
# tasks file for install_2d-apache2
- name: install apache2
  include: install_apache.yml

- name: harden apache configuration
  include: harden_configuration.yml

- name: enable apache2
  include: enable_apache.yml

- name: selinux configuration
  include: selinux_apache.yml
