- name: copy firewall rule
  copy:
   src: ans_emoramgt01kpr.v4
   dest: /etc/fw-2d/rules-available/ans_emoramgt01kpr.v4
   owner: root
   group: root
   mode: '0640'

- name: enable the firewall rule
  file:
   src: /etc/fw-2d/rules-available/ans_emoramgt01kpr.v4
   dest: /etc/fw-2d/rules-enabled/44_ans_emoramgt01kpr.v4
   owner: root
   group: root
   state: link

- name: restart firewall to apply rules
  shell: /usr/local/sbin/firewall-up
