---
# tasks file for install_zenoss user
- name: add zenoss firewall rules
  copy:
    src: ans_snmp-zenoss.v4
    dest: /etc/fw-2d/rules-available/ans_snmp-zenoss.v4
    owner: root
    group: root
    mode: '0600'

- name: apply zenoss firewall rules
  file:
    src: /etc/fw-2d/rules-available/ans_snmp-zenoss.v4
    dest: /etc/fw-2d/rules-enabled/45_ans_snmp-zenoss.v4
    owner: root
    group: root
    state: link

- name: enable the firewall
  shell: /usr/local/sbin/firewall-up
