---
# tasks file for configure_zenoss
- name: configure susr01 snmp user
  include: configure_susr01.yml

- name: configure firewall
  include: firewall.yml

- name: install zenoss
  include: ssh.yml
