---
# tasks file for install_zenoss group
- name: add zenoss ssh rules
  copy:
    src: ans_ssh-zenoss.group
    dest: /etc/ssh/matches-available/ans_ssh-zenoss.group
    owner: root
    group: root
    mode: '0600'

- name: apply zenoss ssh rules
  file:
    src: /etc/ssh/matches-available/ans_ssh-zenoss.group
    dest: /etc/ssh/matches-enabled/15_ans_ssh-zenoss.group
    owner: root
    group: root
    state: link

- name: reload sshd
  shell: /usr/local/sbin/apply_ssh.sh
