---
# tasks file for configure_upguardaccess

- name: Enable firewall
  file:
    src: /etc/fw-2d/rules-available/pkg_ssh-upguard.v4
    dest: /etc/fw-2d/rules-enabled/43_pkg_ssh-upguard.v4
    owner: root
    group: root
    state: link

- name: Add the user 'sec_read
  ansible.builtin.user:
    name: sec_read
    comment: CIS Audit login
    shell: /bin/bash
    uid: 20020
    gid: 20020

- name: Create svc_fixed.upguard@2degrees.nz home dir
  file:
    path: /home/sec_read
    state: directory
    owner: sec_read
    group: users
    mode: '0701'

- name: Create sec_read home dir
  file:
    path: /home/sec_read/.ssh
    state: directory
    owner: sec_read
    group: users
    mode: '0701'

- name: copy over the authorized_keys file
  copy:
    src: authorized_keys
    dest: /home/sec_read/.ssh/authorized_keys
    owner: sec_read
    group: users
    mode: '0644'

- name: copy over the sudoers file
  copy:
    src: ans-sec_read
    dest: /etc/sudoers.d/ans-sec_read
    owner: root
    group: root
    mode: '0440'
    validate: /usr/sbin/visudo -cf %s
