- name: addusrlocalsbin into root $PATH
  lineinfile:
    path: /root/.bashrc
    insertafter: '^# User specific aliases and functions'
    line: export PATH='/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin'
  when: ansible_facts['distribution'] == 'CentOS' or ansible_facts['distribution'] == 'RedHat'

- name: disable firewalld
  systemd:
    name: firewalld
    state: stopped
    enabled: no
  when: ansible_facts['distribution'] == 'CentOS' or ansible_facts['distribution'] == 'RedHat'

- name: copy ifup firewall script
  copy:
    src: 05-firewall-up
    dest: /etc/NetworkManager/dispatcher.d/05-firewall-up
    owner: root
    group: root
    mode: '0755'

- name: Create a symbolic link
  file:
    src: /etc/fw-2d/rules-available/pkg_ssh-upguard.v4
    dest: /etc/fw-2d/rules-enabled/40_pkg_ssh-upguard.v4
    owner: root
    group: root
    state: link

- name: enable the firewall
  shell: /usr/local/sbin/firewall-up
