- name: copy ifup firewall script
  copy:
    src: 05-firewall-up
    dest: /etc/NetworkManager/dispatcher.d/05-firewall-up
    owner: root
    group: root
    mode: '0755'

- name: copy firewall-up script
  copy:
    src: sbin/firewall-up
    dest: /usr/local/sbin/firewall-up
    owner: root
    group: root
    mode: '0700'

- name: copy firewall-down script
  copy:
    src: sbin/firewall-down
    dest: /usr/local/sbin/firewall-down
    owner: root
    group: root
    mode: '0700'

- name: copy fwenrule script
  copy:
    src: sbin/fwenrule
    dest: /usr/local/sbin/fwenrule
    owner: root
    group: root
    mode: '0700'

- name: copy fwmvrule script
  copy:
    src: sbin/fwmvrule
    dest: /usr/local/sbin/fwmvrule
    owner: root
    group: root
    mode: '0700'

- name: copy fwdisrule script
  copy:
    src: sbin/fwdisrule
    dest: /usr/local/sbin/fwdisrule
    owner: root
    group: root
    mode: '0700'
