---
# tasks file for roles/install_2d-firewall
- name: make sure required pacakges are isntalled
  include: preinstall.yml
  ignore_errors: yes

- name: install 2d-firewall
  include: install_2dfirewall.yml
  ignore_errors: yes

- name: enable default firewall rules
  include: enable_default_rules.yml
  ignore_errors: yes

- name: start the firewall
  include: start_firewall.yml
  ignore_errors: yes
