#we should not allow apache on redhat?
#- name: install apache2
#  dnf:
#   name:
#   - httpd
#   - mod_ssl
#   state: latest
- name: install apache2
  apt:
   name:
   - apache2
   state: latest
  when: ansible_facts['distribution'] == 'Ubuntu'


- name: mkdir /var/virtual-hosts
  file:
   path: /var/virtual-hosts
   owner: root
   group: root
   mode: '0755'
