- name: copy default 2d hardening conf
  copy:
   src: conf-available/zz-hardening-options.conf
   dest: /etc/apache2/conf-available/zz-hardening-options.conf
   owner: root
   group: root
   mode: '0644'

- name: copy default 2d default site
  copy:
   src: sites-available/000-2d-default.conf
   dest: /etc/apache2/sites-available/000-2d-default.conf
   owner: root
   group: root
   mode: '0644'

- name: enable 2d default hardening rule
  file:
   src: /etc/apache2/conf-available/zz-hardening-options.conf
   dest: /etc/apache2/conf-enabled/zz-hardening-options.conf
   owner: apache
   group: apache
   state: link

- name: enable 2d default site
  file:
   src: /etc/apache2/sites-available/000-2d-default.conf
   dest: /etc/apache2/sites-enabled/000-2d-default.conf
   owner: apache
   group: apache
   state: link

