---
# tasks file for disable_services
- name: disabled unneeded services
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: no
    state: stopped
  loop: "{{ disabled_services }}"
  ignore_errors: True

- name: Reloaded ansible configs
  ansible.builtin.systemd:
    daemon_reload: yes
