---
# tasks file for configure_upguardaccess

#- name: set dns to ipa server
#  ansible.builtin.command:
#    cmd: systemd-resolve --set-dns=172.24.255.10 --interface=ens160

- name: install ipaclient tools
  ansible.builtin.apt:
    name:
#      - realmd
      - freeipa-client
      - sssd-tools
      - sssd
      - libnss-sss
      - libpam-sss
#      - python-pexpect
      - python3-pexpect
    state: latest
    update_cache: yes
  when: (ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_major_version'] == "20")

#- name: Discovered realm
#  ansible.builtin.command:
#    cmd: /usr/sbin/realm discover "{{ iparealm }}"

#- name: Joint realm
#  ansible.builtin.command:
#    cmd: /usr/sbin/realm join "{{ iparealm }}" --unattended

- name: ipaclientinstall join
#  ansible.builtin.expect:
  ansible.builtin.command:
#    cmd: /usr/sbin/ipa-client-install --ntp-server=ipa-master-stag.2dtest.nz --enable-dns-updates --realm="{{ iparealm }}" -p admin --password="{{ ipapassword }}" --server=ipa-master-stag.2dtest.nz --unattended --ssh-trust-dns --mkhomedir --domain=2dtest.nz
#    cmd: /usr/sbin/ipa-client-install --ntp-server=ipa-master-stag.2dtest.nz --enable-dns-updates --realm="{{ iparealm }}" -p "{{ ipaprincipal }}" --password="{{ ipapassword }}" --server=ipa-master-stag.2dtest.nz --unattended --ssh-trust-dns --mkhomedir --domain="{{ ipadomain }}"
#    cmd: /usr/sbin/ipa-client-install --domain "{{ ipadomain }}" --realm "{{ iparealm }}" --mkhomedir --enable-dns-updates --unattended --force-join --principal "{{ ipaprincipal }}" --ntp-server ipa-master-stag.2dtest.nz --ssh-trust-dns
    argv:
      - /usr/sbin/ipa-client-install
      - --domain
      - "{{ ipadomain }}"
      - --realm
      - "{{ iparealm }}"
      - --mkhomedir
      - --enable-dns-updates
      - --unattended
      - --force-join
      - --principal
      - admin
      - --ntp-server
      - ipa-master-stag.2dtest.nz
      - --ssh-trust-dns
      - -W
    stdin: $%RTFG45rtfg
#    command: /usr/sbin/realm join "{{ iparealm }}"
#    echo: yes
#    responses:
#      (?i)Password for admin: "{{ ipapassword }}"
#      (?i)password: "MySekretPa$$word"
  # you don't want to show passwords in your logs
#  no_log: true
