---
#install for ubuntu crowdstrike

- name: copy over the elastic ca cert
  ansible.builtin.copy:
    src: elastic-ca.crt
    dest: /usr/local/share/ca-certificates/elastic-ca.crt
    owner: root
    group: root
    mode: '0700'
  when: (ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_major_version'] == "8")

- name: copy over the elasticsearch ca cert
  ansible.builtin.copy:
    src: elasticsearch-ca.crt
    dest: /usr/local/share/ca-certificates/elasticsearch-ca.crt
    owner: root
    group: root
    mode: '0700'
  when: (ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_major_version'] == "8")

- name: update ca certs
  ansible.builtin.command: /usr/sbin/update-ca-certificates

- name: Remount a mounted volume and append exec to the existing options
  ansible.posix.mount:
    path: /tmp
    state: remounted
    opts: exec

- name: untar elasticagent
  ansible.builtin.unarchive:
    src: elastic-agent-7.17.7-linux-x86_64.tar.gz
    dest: /tmp/
  when: (ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_major_version'] >= "16")

- name: install elasticagent
  ansible.builtin.command: /tmp/elastic-agent-7.17.7-linux-x86_64/elastic-agent install --url=https://nz-sec-fleet.t3.nz:8220 --enrollment-token=SDA3aEpZY0JLbjhiZ2pYazNPOHk6UFEtSEhYTWxUTS1DSU1fSkt2VTdQZw==


- name: Just force systemd to reread configs (2.4 and above)
  ansible.builtin.systemd:
    daemon_reload: true

- name: Enable service httpd and ensure it is not masked
  ansible.builtin.systemd:
    name: elastic-agent
    enabled: true
    masked: no

- name: restarted elastic-agent
  ansible.builtin.systemd:
    name: elastic-agent
    state: restarted
