##restart services
- name: restart rsyslog
  systemd:
    state: restarted
    enabled: yes
    daemon_reload: yes
    name: rsyslog

- name: restart auditd centos7
  shell: /usr/sbin/service auditd restart
  ignore_errors: yes
  when: (ansible_facts['distribution'] == 'CentOS' and ansible_facts['distribution_major_version'] == "7")

- name: restart auditd centos8
  shell: /usr/sbin/service auditd restart
  ignore_errors: yes
  when: (ansible_facts['distribution'] == 'CentOS' and ansible_facts['distribution_major_version'] == "8")

- name: restart auditd centos8
  shell: /usr/sbin/service auditd restart
  ignore_errors: yes
  when: (ansible_facts['distribution'] == 'RedHat' and ansible_facts['distribution_major_version'] == "8")

- name: restart auditd ubuntu
  systemd:
    state: restarted
    daemon_reload: yes
    name: auditd
  ignore_errors: yes
  when: ansible_facts['distribution'] == 'Ubuntu'
