- name: 5.7 Ensure access to the su command is restricted (Scored)
  pamd:
    name: su
    type: auth
    control: required
    module_path: pam_wheel.so
    module_arguments: 'use_uid'
    state: updated
