- name: install mailx
  package: name=mailx state=latest

- name: configure mailx smtp
  lineinfile:
   path: /etc/mail.rc
   regexp: '^set smtp=smtp://smtp.snap.net.nz:'
   line: set smtp=smtp://smtp.snap.net.nz:25
   create: yes

- name: configure mailx ssl-verify
  lineinfile:
   path: /etc/mail.rc
   line: set ssl-verify=ignore
   create: yes
