- name: install ssl-cert
  package:
   name: ssl-cert
   state: latest
  ignore_errors: yes
  when: ansible_facts['distribution'] == 'Ubuntu'

- name: install openssl
  package:
   name:
    - openssl
    - python3-pyOpenSSL
    - ca-certificates
   state: latest
  ignore_errors: yes
  when: ansible_facts['distribution'] == 'CentOS' or ansible_facts['distribution'] == 'RedHat'
