- name: install ssl-cert
  ansible.builtin.apt:
    name: ssl-cert
    state: latest
    update_cache: yes
  ignore_errors: yes
  when: ansible_facts['distribution'] == 'Ubuntu'

- name: install openssl
  ansible.builtin.dnf:
   name:
    - openssl
    - python3-pyOpenSSL
    - ca-certificates
   state: latest
  ignore_errors: yes
  when: ansible_facts['distribution'] == 'RedHat' and ansible_distribution_version >= '8'

- name: install openssl
  ansible.builtin.yum:
   name:
    - openssl
    - python2-cryptography
    - ca-certificates
   state: latest
  ignore_errors: yes
  vars:
    ansible_python_interpreter: /usr/bin/python2
  when: ansible_facts['distribution'] == 'RedHat' and ansible_distribution_version < '8'
