- name: install ssl-cert
  ansible.builtin.apt:
    name: ssl-cert
    state: latest
    update_cache: yes
  ignore_errors: yes
  when: ansible_facts['distribution'] == 'Ubuntu'

- name: install openssl
  ansible.builtin.dnf:
   name:
    - openssl
    - python3-pyOpenSSL
    - ca-certificates
   state: latest
  ignore_errors: yes
  when: ansible_facts['distribution'] == 'RedHat'
