---
# tasks file for tdm-rkhunter

- name: install rkhunter ubuntu and redhat 8 and above
  package:
    name: "rkhunter"
    state: present
  when: (ansible_facts['distribution'] == "Ubuntu") or
        (ansible_facts['distribution'] == 'RedHat' and ansible_distribution_version >= '8')

- name: install rkhunter redhat 7 and below
  yum:
    name: "rkhunter"
    state: present
  vars:
    ansible_python_interpreter: /usr/bin/python2
  when: ansible_facts['distribution'] == 'RedHat' and ansible_distribution_version < '8'

- name: RH create logrotate file if not exist
  copy:
    src: rh_logrotate_rkhunter
    dest: /etc/logrotate.d/rkhunter
    owner: root
    group: root
    mode: 0644
    force: no
  when: ansible_facts['distribution'] == "RedHat"

- name: UB create logrotate file if not exist
  copy:
    src: rh_logrotate_rkhunter
    dest: /etc/logrotate.d/rkhunter
    owner: root
    group: root
    mode: 0644
    force: no
  when: (ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_major_version'] >= "18")

- name: RH permissions for rkhunter directory
  file:
    group: adm
    owner: root
    mode: 02750
    path: /var/log/rkhunter
    state: directory
  when: ansible_facts['distribution'] == "RedHat"

- name: UB permissions for rkhunter directory
  file:
    group: adm
    owner: syslog
    mode: 02750
    path: /var/log/rkhunter
    state: directory
  when: (ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_major_version'] >= "18")


- name: configure logfile
  lineinfile:
    path: /etc/rkhunter.conf
    regexp: ^LOGFILE=
    line: LOGFILE=/var/log/rkhunter/rkhunter.log

- name: configure append to logfile
  lineinfile:
    path: /etc/rkhunter.conf
    insertafter: ^#APPEND_LOG=
    regexp: ^APPEND_LOG=
    line: APPEND_LOG=1

- name: check for misplaced logfile
  stat:
    path: /var/log/rkhunter.log
  register: rk_log_loc

- name: copy log file to correct directory
  copy:
    dest: /var/log/rkhunter/rkhunter.log
    remote_src: yes
    src: /var/log/rkhunter.log
  when: rk_log_loc.stat.exists
  notify: cleanup

- name: RH permissions for rkhunter file
  file:
    group: adm
    owner: root
    mode: 0640
    path: /var/log/rkhunter/rkhunter.log
    state: touch
  when: ansible_facts['distribution'] == "RedHat"

- name: UB permissions for rkhunter file
  file:
    group: adm
    owner: syslog
    mode: 0640
    path: /var/log/rkhunter/rkhunter.log
    state: touch
  when: (ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_major_version'] >= "18")

- name: rkhunter propupd prerun
  command: rkhunter --propupd
