---
#install for ubuntu crowdstrike
- name: copy over the crowdstrike deb file
  ansible.builtin.copy:
    src: falcon-sensor_6.50.0-14713_amd64.Ubuntu.deb
    dest: /tmp/falcon-sensor_6.50.0-14713_amd64.Ubuntu.deb
    owner: root
    group: root
    mode: '0700'
  when: (ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_major_version'] >= "16")

- name: Install crowdstrike
  apt:
    deb: /tmp/falcon-sensor_6.50.0-14713_amd64.Ubuntu.deb
  when: (ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_major_version'] >= "16")

- name: delete the installer
  ansible.builtin.file:
    path: /tmp/falcon-sensor_6.50.0-14713_amd64.Ubuntu.deb
    state: absent
  when: (ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_major_version'] >= "16")

- name: configure crowdstrike
#2degrees proxy
  ansible.builtin.command: /opt/CrowdStrike/falconctl -s --aph=2dproxy.2degrees.nz --app=8080 --apd=FALSE --cid=8DF946AEEA7B4D35B6C822853CD822B0-94
#frigg proxy
#  ansible.builtin.command: /opt/CrowdStrike/falconctl -s --aph=frigg.2degrees.nz --app=3128 --apd=FALSE --cid=8DF946AEEA7B4D35B6C822853CD822B0-94


- name: Just force systemd to reread configs (2.4 and above)
  ansible.builtin.systemd:
    daemon_reload: true

- name: Enable service httpd and ensure it is not masked
  ansible.builtin.systemd:
    name: falcon-sensor
    enabled: true
    masked: no

- name: restarted crowdstrike
  ansible.builtin.systemd:
    name: falcon-sensor
    state: restarted
