---
# tasks file for setting up access to the server
- name: remove ssh_host_ed25519_key.pub from ansilbe server now
  delegate_to: 127.0.0.1
  file: 
    path: "{{ item }}"
    state: absent
  loop:
    - '../tmp/{{inventory_hostname}}_ssh_host_ed25519_key'
    - '../tmp/{{inventory_hostname}}_ssh_host_ed25519_key.pub'
    - '../tmp/{{inventory_hostname}}_ssh_host_ed25519_key-cert.pub'
    - '../tmp/{{inventory_hostname}}_ssh_host_ecdsa_key'
    - '../tmp/{{inventory_hostname}}_ssh_host_ecdsa_key.pub'
    - '../tmp/{{inventory_hostname}}_ssh_host_ecdsa_key-cert.pub'


- name: generate a server ed25519 host key
  delegate_to: 127.0.0.1
  command: /usr/bin/ssh-keygen -t ed25519 -N "" -f ../tmp/{{inventory_hostname}}_ssh_host_ed25519_key

- name: generate a server ecdsa host key
  delegate_to: 127.0.0.1
  command: /usr/bin/ssh-keygen -t ed25519 -N "" -f ../tmp/{{inventory_hostname}}_ssh_host_ecdsa_key

- name: sign the ed25519 hostkey
  delegate_to: 127.0.0.1
  command: /usr/bin/ssh-keygen -s ../tmp/server_ca -I 2degrees-server_{{ vm_shortname }} -h -n {{ vm_shortname }}.2dl.nz,{{ vm_shortname }}.2degrees.nz,{{ vm_shortname }}.nzc.co.nz -P {{ ca_passphrase }} -V +300w ../tmp/{{inventory_hostname}}_ssh_host_ed25519_key.pub

- name: sign the ecdsa hostkey
  delegate_to: 127.0.0.1
  command: /usr/bin/ssh-keygen -s ../tmp/server_ca -I 2degrees-server_{{ vm_shortname }} -h -n {{ vm_shortname }}.2dl.nz,{{ vm_shortname }}.2degrees.nz,{{ vm_shortname }}.nzc.co.nz -P {{ ca_passphrase }} -V +300w ../tmp/{{inventory_hostname}}_ssh_host_ecdsa_key.pub
