- name: nsswitch.conf passwd mysql
  lineinfile:
   path: /etc/nsswitch.conf
   regex: '^(passwd:.*compat systemd)'
   line: '\1 mysql'
   backrefs: yes

- name: nsswitch.conf group mysql
  lineinfile:
   path: /etc/nsswitch.conf
   regex: '^(group:.*compat systemd)'
   line: '\1 mysql'
   backrefs: yes

- name: nsswitch.conf shadow mysql
  lineinfile:
   path: /etc/nsswitch.conf
   regex: '^(shadow:.*compat)'
   line: '\1 mysql'
   backrefs: yes

- name: put the new password into the pam_radius_auth.conf file
  replace:
    path: /etc/pam_radius_auth.conf
    regexp: '^(.*)PASSWORD(.*)$'
    replace: '\g<1>{{ vm_radius_secret }}\g<2>'

#- name: generate the radius secret
#  command: echo {{ hostvars['localhost']['radius_secret'] }} > /etc/pam_radius_auth.conf
