- name: Install the xz-utils as it's needed to install splunk to make it present
  apt:
   name: xz-utils
   state: present
   update_cache: yes
  ignore_errors: yes
  when: ansible_facts['distribution'] == 'Ubuntu'

- name: Install sysstat ubuntu
  apt:
   name: sysstat
   state: present
   update_cache: yes
  ignore_errors: yes
  when: ansible_facts['distribution'] == 'Ubuntu'

- name: Install systat centos
  yum:
   name: sysstat
   state: present
  ignore_errors: yes
  when: ansible_facts['distribution'] == 'CentOS'

- name: Install systat redhat
  yum:
   name: sysstat
   state: present
  ignore_errors: yes
  when: ansible_facts['distribution'] == 'RedHat'
