---
# tasks file for deploy_splunkforwarder
#learn what packages are installed
- name: Make sure splunk server package is not already installed
  package_facts:
    manager: auto
  when: (ansible_facts['distribution'] == "Ubuntu") or
        (ansible_facts['distribution'] == 'RedHat' and ansible_distribution_version >= '8')

- name: Make sure splunk server package is not installed redhat 7 or below
  package_facts:
    manager: auto
  vars:
    ansible_python_interpreter: /usr/bin/python2
  when: ansible_facts['distribution'] == 'RedHat' and ansible_distribution_version < '8'

- name: install extra software
  import_tasks: extra_software.yml

- name: run splunk install tasks
  import_tasks: install_splunkforwarder.yml
#  when:
#    - "'splunkforwarder' not in ansible_facts.packages"

- name: deploy configs
  import_tasks: configure_splunk.yml

- name: splunk user
  import_tasks: configure_user.yml

- name: update firewall
  import_tasks: configure_firewall.yml

#- name: enable splunk
#  import_tasks: enable_splunk.yml

#- name: configure selinux
#  import_tasks: configure_selinux.yml
