- name: 5.1.2 crontab permissions
  file:
    path: /etc/crontab
    owner: root
    group: root
    mode: '0600'

- name: 5.1.3 cron.hourly
  file:
    path: /etc/cron.hourly
    owner: root
    group: root
    mode: '0700'

- name: 5.1.4 cron.daily
  file:
    path: /etc/cron.daily
    owner: root
    group: root
    mode: '0700'

- name: 5.1.5 cron.weekly
  file:
    path: /etc/cron.weekly
    owner: root
    group: root
    mode: '0700'

- name: 5.1.6 cron.monthly
  file:
    path: /etc/cron.monthly
    owner: root
    group: root
    mode: '0700'

- name: 5.1.7 cron.d
  file:
    path: /etc/cron.daily
    owner: root
    group: root
    mode: '0700'

- name: 5.1.8 cron.deny removal
  file:
    path: /etc/cron.deny
    state: absent

- name: 5.1.8 cron.allow
  file:
    path: /etc/cron.allow
    owner: root
    group: root
    mode: '0600'
    state: touch

- name: 5.1.8 at.deny removal
  file:
    path: /etc/at.deny
    state: absent

- name: 5.1.8 at.allow
  file:
    path: /etc/at.allow
    owner: root
    group: root
    mode: '0600'
    state: touch
