---
# tasks file for configure_upguardaccess

- name: copy the firewall rule to the server
  ansible.builtin.copy:
    src: firewall-rules-available/ans_ssh-jumphost.v4
    dest: /etc/fw-2d/rules-available/ans_ssh-jumphost.v4
    owner: root
    group: root
    mode: '0400'

- name: Enable firewall rule
  file:
    src: /etc/fw-2d/rules-available/ans_ssh-jumphost.v4
    dest: /etc/fw-2d/rules-enabled/33_ans_ssh-jumphost.v4
    owner: root
    group: root
    state: link

- name: enable the firewall
  shell: /usr/local/sbin/firewall-up

- name: copy the ender ssh match rule to the server
  ansible.builtin.copy:
    src: ssh-matches-available/ans_ender.address
    dest: /etc/ssh/matches-available/ans_ender.address
    owner: root
    group: root
    mode: '0400'

- name: copy the alai ssh match rule to the server
  ansible.builtin.copy:
    src: ssh-matches-available/ans_alai.address
    dest: /etc/ssh/matches-available/ans_alai.address
    owner: root
    group: root
    mode: '0400'

- name: copy the bean ssh match rule to the server
  ansible.builtin.copy:
    src: ssh-matches-available/ans_bean.address
    dest: /etc/ssh/matches-available/ans_bean.address
    owner: root
    group: root
    mode: '0400'

- name: copy the ans_jumphosts-systems.group ssh match rule to the server
  ansible.builtin.copy:
    src: ssh-matches-available/ans_jumphosts-systems.group
    dest: /etc/ssh/matches-available/ans_jumphosts-systems.group
    owner: root
    group: root
    mode: '0400'

- name: copy the ans_jumphosts-networks.group ssh match rule to the server
  ansible.builtin.copy:
    src: ssh-matches-available/ans_jumphosts-networks.group
    dest: /etc/ssh/matches-available/ans_jumphosts-networks.group
    owner: root
    group: root
    mode: '0400'

- name: Enable ender ssh match rule
  file:
    src: /etc/ssh/matches-available/ans_ender.address
    dest: /etc/ssh/matches-enabled/15_ans_ender.address
    owner: root
    group: root
    state: link

- name: Enable alai ssh match rule
  file:
    src: /etc/ssh/matches-available/ans_alai.address
    dest: /etc/ssh/matches-enabled/15_ans_alai.address
    owner: root
    group: root
    state: link

- name: Enable bean ssh match rule
  file:
    src: /etc/ssh/matches-available/ans_bean.address
    dest: /etc/ssh/matches-enabled/15_ans_bean.address
    owner: root
    group: root
    state: link

- name: Enable zenoss ssh match rule
  file:
    src: /etc/ssh/matches-available/ans_jumphosts-networks.group
    dest: /etc/ssh/matches-enabled/10_ans_jumphosts-networks.group
    owner: root
    group: root
    state: link

- name: Enable autodiscover ssh match rule
  file:
    src: /etc/ssh/matches-available/ans_jumphosts-systems.group
    dest: /etc/ssh/matches-enabled/10_ans_jumphosts-systems.group
    owner: root
    group: root
    state: link

- name: apply the ssh enabled rules
  shell: /usr/local/sbin/apply_ssh.sh
