---
# tasks file for configure_autodiscover

- name: copy sshd matches rule
  copy:
    src: ans_autodiscover.user
    dest: /etc/ssh/matches-available/ans_autodiscover.user
    owner: root
    group: root
    mode: '0640'

- name: Enable ssh matches rule
  file:
    src: /etc/ssh/matches-available/ans_autodiscover.user
    dest: /etc/ssh/matches-enabled/10_ans_autodiscover.user
    owner: root
    group: root
    state: link

- name: copy firewall rule
  copy:
    src: ans_ssh-autodiscover.v4
    dest: /etc/fw-2d/rules-available/ans_ssh-autodiscover.v4
    owner: root
    group: root
    mode: '0640'

- name: Enable firewall rule
  file:
    src: /etc/fw-2d/rules-available/ans_ssh-autodiscover.v4
    dest: /etc/fw-2d/rules-enabled/43_ans_ssh-autodiscover.v4
    owner: root
    group: root
    state: link


- name: Create svc_autodiscover-unix home dir
  file:
    path: /home/svc_autodiscover-unix
    state: directory
    owner: svc_autodiscover-unix
    group: users
    mode: '0701'

- name: Create svc_autodiscover-unix ssh dir
  file:
    path: /home/svc_autodiscover-unix/.ssh
    state: directory
    owner: svc_autodiscover-unix
    group: users
    mode: '0701'

- name: copy over the authorized_keys file
  copy:
    src: authorized_keys
    dest: /home/svc_autodiscover-unix/.ssh/authorized_keys
    owner: svc_autodiscover-unix
    group: users
    mode: '0644'

- name: run the apply_ssh.sh script
  shell: /usr/local/sbin/apply_ssh.sh
