---
# tasks file for configure_upguardaccess

- name: restarted nscd so we can get the groups
  ansible.builtin.service:
    name: nscd
    state: restarted
  when: (ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_major_version'] == "18") or
        (ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_major_version'] == "16")

- name: copied sshd matches rule
  ansible.builtin.template:
    src: ans_autodiscover.user.j2
    dest: /etc/ssh/matches-available/ans_autodiscover.user
    owner: root
    group: root
    mode: '0640'

- name: Enabled ssh matches rule
  file:
    src: /etc/ssh/matches-available/ans_autodiscover.user
    dest: /etc/ssh/matches-enabled/10_ans_autodiscover.user
    owner: root
    group: root
    state: link

- name: copied firewall rule
  copy:
    src: ans_ssh-autodiscover.v4
    dest: /etc/fw-2d/rules-available/ans_ssh-autodiscover.v4
    owner: root
    group: root
    mode: '0640'

- name: Enabled firewall rule
  ansible.builtin.file:
    src: /etc/fw-2d/rules-available/ans_ssh-autodiscover.v4
    dest: /etc/fw-2d/rules-enabled/43_ans_ssh-autodiscover.v4
    owner: root
    group: root
    state: link


- name: Created home dir
  file:
    path: /home/"{{ autodiscover_user }}""
    state: directory
    owner: "{{ autodiscover_user }}"
    group: users
    mode: '0701'
  when: (ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_major_version'] == "18") or
        (ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_major_version'] == "16")

- name: Created ssh dir
  file:
    path: /home/"{{ autodiscover_user }}"/.ssh
    state: directory
    owner: "{{ autodiscover_user }}"
    group: users
    mode: '0701'
  when: (ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_major_version'] == "18") or
        (ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_major_version'] == "16")

- name: copied over the authorized_keys file
  copy:
    src: authorized_keys
    dest: /home/"{{ autodiscover_user }}"/.ssh/authorized_keys
    owner: "{{ autodiscover_user }}"
    group: users
    mode: '0644'
  when: (ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_major_version'] == "18") or
        (ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_major_version'] == "16")

- name: ran the apply_ssh.sh script
  shell: /usr/local/sbin/apply_ssh.sh
