---
# tasks file for configure_upguardaccess

- name: restart nscd so we can get the groups
  ansible.builtin.service:
    name: nscd
    state: restarted

- name: copy sshd matches rule
  copy:
    src: ans_device42.user
    dest: /etc/ssh/matches-available/ans_device42.user
    owner: root
    group: root
    mode: '0640'

- name: Enable ssh matches rule
  file:
    src: /etc/ssh/matches-available/ans_device42.user
    dest: /etc/ssh/matches-enabled/10_ans_device42.user
    owner: root
    group: root
    state: link

- name: copy firewall rule
  copy:
    src: ans_ssh-device42.v4
    dest: /etc/fw-2d/rules-available/ans_ssh-device42.v4
    owner: root
    group: root
    mode: '0640'

- name: Enable firewall rule
  file:
    src: /etc/fw-2d/rules-available/ans_ssh-device42.v4
    dest: /etc/fw-2d/rules-enabled/43_ans_ssh-device42.v4
    owner: root
    group: root
    state: link


- name: Create svc_d42_unix@2degrees.nz home dir
  file:
    path: /home/svc_d42_unix@2degrees.nz
    state: directory
    owner: svc_d42_unix@2degrees.nz
    group: users
    mode: '0701'

- name: Create svc_d42_unix@2degrees.nz home dir
  file:
    path: /home/svc_d42_unix@2degrees.nz/.ssh
    state: directory
    owner: svc_d42_unix@2degrees.nz
    group: users
    mode: '0701'

- name: copy over the authorized_keys file
  copy:
    src: authorized_keys
    dest: /home/svc_d42_unix@2degrees.nz/.ssh/authorized_keys
    owner: svc_d42_unix@2degrees.nz
    group: users
    mode: '0644'

- name: run the apply_ssh.sh script
  shell: /usr/local/sbin/apply_ssh.sh
