---
- name: install ipaclient tools
  ansible.builtin.apt:
    name:
      - freeipa-client
      - sssd-tools
      - sssd
      - libnss-sss
      - libpam-sss
      - python3-pexpect
    state: latest
    update_cache: yes
  when: (ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_major_version'] == "20")

- name: ipaclientinstall join
  ansible.builtin.command:
    argv:
      - /usr/sbin/ipa-client-install
      - --domain
      - "{{ ipadomain }}"
      - --realm
      - "{{ iparealm }}"
      - --mkhomedir
      - --enable-dns-updates
      - --unattended
      - --force-join
      - --principal
      - "{{ ipaprincipal }}"
      - --ntp-server
      - ipamasterakl.2dl.nz
      - --ssh-trust-dns
      - -W
    stdin: "{{ ipapassword }}"
  # you don't want to show passwords in your logs
  no_log: true
