- name: make sure useful tools are installed redhat and centos
  dnf:
    name:
    - nmap
    - tree
    - htop
    - iotop
    - mtr
    - tcpdump
    - ipcalc
    - open-vm-tools
    - nano
    - python3
    - mlocate
    - pwgen
    - rsync
    - bind-utils
    state: present
  when: ansible_facts['distribution'] == 'RedHat' and ansible_distribution_version >= '8'

- name: make sure useful tools are installed redhat 7 and below
  yum:
    name:
    - nmap
    - tree
#    - htop
    - iotop
    - mtr
    - tcpdump
#    - ipcalc
    - open-vm-tools
    - nano
    - python3
    - mlocate
#    - pwgen
    - rsync
    - bind-utils
    state: present
  vars:
    ansible_python_interpreter: /usr/bin/python2
  when: ansible_facts['distribution'] == 'RedHat' and ansible_distribution_version < '8'

- name: make sure useful tools are installed ubuntu
  apt:
    name: 
    - nmap
    - tree
    - htop
    - iotop
    - mtr-tiny
    - tcpdump
    - ipcalc
    - open-vm-tools
    - nano
    - python3
    - mlocate
    - pwgen
    - rsync
    state: present
  when: ansible_facts['distribution'] == 'Ubuntu'

- name: Copy apache2.nanorc
  ansible.builtin.copy:
    src: apache2.nanorc
    dest: /usr/share/nano/apache2.nanorc
    owner: root
    group: root
    mode: '0644'

- name: Copy markdown.nanorc
  ansible.builtin.copy:
    src: markdown.nanorc
    dest: /usr/share/nano/markdown.nanorc
    owner: root
    group: root
    mode: '0644'
