###
#removing old repos
###
# Example removing a repository and cleaning up metadata cache
##
#Ubuntu
##

- name: ubuntu16 repo
  copy:
   src: sources.list.16
   dest: /etc/apt/sources.list
   owner: root
   group: root
   mode: '0644'
  ignore_errors: yes
  when: ansible_facts['distribution'] == 'Ubuntu' and ansible_distribution_major_version == '16'

- name: ubuntu18 repo
  copy:
   src: sources.list.18
   dest: /etc/apt/sources.list
   owner: root
   group: root
   mode: '0644'
  ignore_errors: yes
  when: ansible_facts['distribution'] == 'Ubuntu' and ansible_distribution_major_version == '18'

- name: ubuntu20 repo
  copy:
   src: sources.list.20
   dest: /etc/apt/sources.list
   owner: root
   group: root
   mode: '0644'
  ignore_errors: yes
  when: ansible_facts['distribution'] == 'Ubuntu' and ansible_distribution_major_version == '20'

- name: ubuntu22 repo
  copy:
   src: sources.list.22
   dest: /etc/apt/sources.list
   owner: root
   group: root
   mode: '0644'
  ignore_errors: yes
  when: ansible_facts['distribution'] == 'Ubuntu' and ansible_distribution_major_version == '22'

- name: 2d ubuntu repo
  copy:
   src: 2d.list
   dest: /etc/apt/sources.list.d/2d.list
   owner: root
   group: root
   mode: '0644'
  ignore_errors: yes
  when: ansible_facts['distribution'] == 'Ubuntu' and ansible_distribution_major_version <= '18'

- name: 2d repo apt key
  apt_key:
    url: http://repo.snap.net.nz/2d-packages/public/pubrepo.gpg
    state: present
  ignore_errors: yes
  when: ansible_facts['distribution'] == 'Ubuntu'

#- name: Run the equivalent of "apt-get update"
#  apt:
#    update_cache: yes
#  ignore_errors: yes
#  when: ansible_facts['distribution'] == 'Ubuntu'
