---
# handlers file for deploy_ubuntu18
- name: Generating Netplan Configuration
  command: netplan generate
  listen: netplan generate config
  notify: netplan apply config
  become: true

- name: Applying Netplan Configuration
  command: netplan apply
  async: 45
  poll: 5
  listen: netplan apply config
  become: true
#  when: netplan_apply

#  notify: netplan generate config
#  notify: netplan apply config
