- name: enable journald output to syslog
  lineinfile:
    path: /etc/systemd/journald.conf
    regexp: '^#ForwardToSyslog=no'
    line: ForwardToSyslog=yes

- name: restart journald
  systemd:
    state: restarted
    name: systemd-journald
