- name: Ensure /opt/splunkforwarder/etc/apps/all_devices_fixed/local folder exists
  file:
   path: /opt/splunkforwarder/etc/apps/all_devices_fixed/local
   state: directory
   recurse: yes


- name: apps app.conf
  copy:
   src: appsconf/app.conf
   dest: /opt/splunkforwarder/etc/apps/all_devices_fixed/local/app.conf
   owner: splunk
   group: splunk
   mode: '0644'
- name: apps deploymentclient.conf
  copy:
   src: appsconf/deploymentclient.conf
   dest: /opt/splunkforwarder/etc/apps/all_devices_fixed/local/deploymentclient.conf
   owner: splunk
   group: splunk
   mode: '0644'
- name: apps inputs.conf.empty
  copy:
   src: appsconf/inputs.conf.empty
   dest: /opt/splunkforwarder/etc/apps/all_devices_fixed/local/inputs.conf.empty
   owner: splunk
   group: splunk
   mode: '0644'
- name: apps outputs.conf
  copy:
   src: appsconf/outputs.conf
   dest: /opt/splunkforwarder/etc/apps/all_devices_fixed/local/outputs.conf
   owner: splunk
   group: splunk
   mode: '0644'
- name: apps props.conf.empty
  copy:
   src: appsconf/props.conf.empty
   dest: /opt/splunkforwarder/etc/apps/all_devices_fixed/local/props.conf.empty
   owner: splunk
   group: splunk
   mode: '0644'
- name: apps user-seed.conf
  copy:
   src: systemconf/user-seed.conf
   dest: /opt/splunkforwarder/etc/system/local/user-seed.conf
   owner: splunk
   group: splunk
   mode: '0644'
- name: apps web.conf
  copy:
   src: systemconf/web.conf
   dest: /opt/splunkforwarder/etc/system/local/web.conf
   owner: splunk
   group: splunk
   mode: '0640'

- name: Ensure /opt/splunkforwarder/ is owned by splunk
  file:
   path: /opt/splunkforwarder/
   state: directory
   recurse: yes
   owner: splunk

