- name: accept the licence
  shell: /opt/splunkforwarder/bin/splunk enable boot-start --accept-license --answer-yes --no-prompt -user splunk

- name: stop the slunk service
  service:
    name: splunk.service
    state: stopped

- name: accept the licence
  shell: /opt/splunkforwarder/bin/splunk enable boot-start --accept-license --answer-yes --no-prompt -user splunk

- name: start splunk
  service:
    name: splunk.service
    enabled: yes
    state: started
