---
# tasks file for configure_ubuntu_subscription

#https://butwt.wordpress.com/2020/01/24/anisble-apt-proxies/
- name: Add esm Repo Key for the initial install, we use our own later
  command:
   argv:
    - /usr/bin/apt-key
    - adv
    - --keyserver-options
    - http-proxy=http://frigg.snap.net.nz:3128
    - --keyserver
    - hkp://keyserver.ubuntu.com:80
    - --recv-keys
    - 56F7650A24C9E9ECF87C4D8D4067E40313CB4B13

- name: installed landscape-client
  ansible.builtin.apt:
    name: 
      - landscape-client
      - ubuntu-advantage-tools
    update_cache: yes
    state: latest

- name: registered to canonical landscape onprem
  shell: /usr/bin/landscape-config --silent -t "{{ vm_shortname }}" -a standalone -u https://landscape.2degrees.nz/message-system --ping-url http://landscape.2degrees.nz/ping

- name: Ensure http proxy is set for ua
  ansible.builtin.lineinfile:
    path: /etc/ubuntu-advantage/uaclient.conf
    regexp: '^  http_proxy:'
    line: '  http_proxy: http://frigg.snap.net.nz:3128'

- name: Ensure http proxy is set for ua
  ansible.builtin.lineinfile:
    path: /etc/ubuntu-advantage/uaclient.conf
    regexp: '^  https_proxy:'
    line: '  https_proxy: http://frigg.snap.net.nz:3128'

- name: Create  /etc/apt/keyrings/ if it does not exist
  ansible.builtin.file:
    path: /etc/apt/keyrings/
    state: directory
    mode: '0755'

- name: copied esm pub file
  copy:
    src: esm.pub
    dest: /etc/apt/keyrings/esm.pub
    owner: root
    group: root
    mode: '0644'

- name: copied esm conf proxy file
  copy:
    src: esmproxy
    dest: /etc/apt/apt.conf.d/05esmproxy
    owner: root
    group: root
    mode: '0600'
  when: ansible_facts['distribution'] == 'Ubuntu' and ansible_distribution_version != '22.03'

- name: copied esm_repo.list
  ansible.builtin.template:
    src: esm_repo.list.j2
    dest: /etc/apt/sources.list.d/05_esm_repo.list
    owner: root
    group: root
    mode: '0600'
  when: ansible_facts['distribution'] == 'Ubuntu' and ansible_distribution_version != '22.03'


- name: attach the ua
  shell: env https_proxy="http://frigg.snap.net.nz:3128" /usr/bin/ua attach "{{ advantageregistrationkey }}"

- name: make sure ubuntu-esm-infra.list doesn't exist
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/ubuntu-esm-infra.list
    state: absent

