- name: Install zenoss on ubuntu 18.04 servers and newer
  hosts: cgnatdnsdocker
  remote_user: dave.gardner@2degrees.nz
  become: yes
  become_method: sudo
  gather_facts: true
  ignore_unreachable: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - install_2dsnmpd
#    - install_zenoss
