#how to run this playbook
#ansible-playbook playbooks/install_2dradiusauth.yml --ask-vault-pass
- name: install 2d-utils
  hosts: ubuntu18radius
#  remote_user: zeus
  remote_user: dave.gardner
  become: yes
  become_method: sudo
  ignore_unreachable: true
  #how many to run at once
  serial: 1
  vars:
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - install_2dradiusauth
    - permissions_sudo-sysadmin
    - permissions_sudo-techm
