#!/bin/bash

#Script executed by systemd clamav.service
#Ricky Owens 20190125

ConfLocation="/etc/clamav/2d-conf.d/"
IncludeConf="/etc/clamav/2d-include.conf"
LogFile="/tmp/clamav-$(date +'%Y-%m-%d').log";
EMAIL_MSG="Please see the log file attached.";
EMAIL_FROM="no-reply@snap.net.nz";
EMAIL_TO="sysadmin@2degrees.nz";


#Build the 2d-include.conf file
rm $IncludeConf
echo "#Autogenerated file, do not manually change me as any changes will be overwritten" > $IncludeConf
i=0
while read line
do
        #Append contents of found include file into autogenerated include file
        cat "$ConfLocation$line" >> $IncludeConf
        (( i++ ))
done < <(ls $ConfLocation | grep .include)

# Run scan
#Scan only included folders and only executable binaries in those folders, and be nice to the cpu and io about it
ionice -c3 nice -n 19 /usr/bin/clamscan -ri --scan-elf=yes --file-list=$IncludeConf | tee "$LogFile";
#clamscan -ri --exclude-dir=^/sys --exclude-dir=^/dev --exclude-dir=^/proc / | tee "$LogFile";

# Check log for "Infected" Lines
MALWARE=$(tail "$LogFile"|grep Infected|cut -d" " -f3);

# If value not equal to zero, send email
if [ "$MALWARE" -ne "0" ]; then
 echo "Infected file found, sending email to $EMAIL_TO";
 echo "$EMAIL_MSG"|mail -a "$LogFile" -s "Malware Found on $HOSTNAME!" -r "$EMAIL_FROM" "$EMAIL_TO";
fi

#Remove temp log file
rm $LogFile

exit 0
