- name: restart service clamav, in all cases, also issue daemon-reload to pick up config changes
  systemd:
    state: restarted
    daemon_reload: yes
    name: clamav
    enabled: yes
    masked: no

- name: enable clamav timer
  systemd:
    name: clamav.timer
    state: started
    enabled: True
