---
# tasks file for install_ntp
- name: Install chrony
  apt:
    name: chrony
    state: present

- name: add include /etc/chrony/chrony.conf.d/*.conf
  lineinfile:
   path: /etc/chrony/chrony.conf
   regexp: '^include .*'
   line: include /etc/chrony/chrony.conf.d/*.conf
   state: present

- name: add chrony.conf.d
  file:
    path: /etc/chrony/chrony.conf.d
    state: directory
    mode: '0755'

- name: copy 10-ad-client.conf
  copy:
    src: chrony.conf.d/10-ad-client.conf
    dest: /etc/chrony/chrony.conf.d/10-ad-client.conf
    owner: root
    group: root
    mode: '0640'

- name: remove pool options
  replace:
    path: /etc/chrony/chrony.conf
    regexp: '^pool (.*)'
    replace: '#pool \1'

- name: Make sure chrony is restarted
  systemd:
    state: restarted
    name: chrony
