---
# tasks file for configure_upguardaccess

- name: UB restart nscd so we can get the groups
  ansible.builtin.service:
    name: nscd
    state: restarted

- name: UB copy ssh matches rule
  copy:
    src: ans_jenkins.group
    dest: /etc/ssh/matches-available/ans_jenkins.group
    owner: root
    group: root
    mode: '0640'

- name: UB Enable ssh matches rule
  file:
    src: /etc/ssh/matches-available/ans_jenkins.group
    dest: /etc/ssh/matches-enabled/10_ans_jenkins.group
    owner: root
    group: root
    state: link

- name: UB copy firewall rule
  copy:
    src: ans_jenkins.v4
    dest: /etc/fw-2d/rules-available/ans_jenkins.v4
    owner: root
    group: root
    mode: '0640'

- name: UB Enable firewall rule
  file:
    src: /etc/fw-2d/rules-available/ans_jenkins.v4
    dest: /etc/fw-2d/rules-enabled/43_ans_jenkins.v4
    owner: root
    group: root
    state: link


- name: UB Create svc_jenkinsfixeddev@2degrees.nz home dir
  file:
    path: /home/svc_jenkinsfixeddev@2degrees.nz
    state: directory
    owner: svc_jenkinsfixeddev@2degrees.nz
    group: users
    mode: '0701'

- name: UB Create svc_jenkinsfixeddev@2degrees.nz home dir
  file:
    path: /home/svc_jenkinsfixeddev@2degrees.nz/.ssh
    state: directory
    owner: svc_jenkinsfixeddev@2degrees.nz
    group: users
    mode: '0701'

- name: UB copy over the authorized_keys file
  copy:
    src: authorized_keys
    dest: /home/svc_jenkinsfixeddev@2degrees.nz/.ssh/authorized_keys
    owner: svc_jenkinsfixeddev@2degrees.nz
    group: users
    mode: '0644'

- name: UB copy over the sudoers file
  copy:
    src: ans-jenkins
    dest: /etc/sudoers.d/ans-jenkins
    owner: root
    group: root
    mode: '0440'
    validate: /usr/sbin/visudo -cf %s

- name: UB run the apply_ssh.sh script
  shell: /usr/local/sbin/apply_ssh.sh

- name: UB run the firewall-up script
  shell: /usr/local/sbin/firewall-up
