#!/bin/bash

BASEDIR="/etc/ssh"

#Make sure we are running as root
if [ "$EUID" -ne 0 ]
  then echo "Please run as root"
  exit
fi

RULESAVAILABLE="$BASEDIR/matches-available"
RULESENABLED="$BASEDIR/matches-enabled"

echo "----------------------"
echo ""

echo "Available Match Rules"
echo "----------------------"
echo ""
#pushd to the rules available dir so we can autocomplete the read command using "-e"
pushd $RULESAVAILABLE
ls $RULESAVAILABLE
read -e -r -p $'Type the name of the rule you want to enable : ' rulechoice
rulechoice=${rulechoice,,}
RULE=$rulechoice

if [[ "$RULE" == *".address" ]]
then
        V=address
fi
if [[ "$RULE" == *".user" ]]
then
        V=user
fi
if [[ "$RULE" == *".group" ]]
then
        V=group
fi
popd
        echo "currently enabled rules"
        echo "----------------------"
        echo ""
        ls $RULESENABLED | grep "$V"
        echo "What position do you want to give the rule?"
        echo "What position do you want to give the rule?"
        read -r -p $'Type a number : ' position
        position=${position,,}
        POSITION=$position

        echo "----------------------"
        echo ""
        #echo "Position:$POSITION"
        #echo "ln -s $RULESAVAILABLE/$RULE $RULESENABLED/${POSITION}_$RULE"
        ln -s $RULESAVAILABLE/$RULE $RULESENABLED/${POSITION}_$RULE

        echo "Updated enabled rules"
        echo "----------------------"
        echo ""
        ls $RULESENABLED | grep "$V"
        echo ""
        echo "----------------------"
        echo ""

echo "YOU NOW NEED TO RUN apply_ssh.sh"

exit 0
