---
# tasks file for install_zenoss user

- name: copied adabsentadmin matches file if it didn't exist already
  copy:
    src: ans_ssh-rh-adabsentadmin.group
    dest: /etc/ssh/matches-available/ans_ssh-rh-adabsentadmin.group
    owner: root
    group: root
    mode: '0600'

- name: copied adabsentuser matches file if it didn't exist already
  copy:
    src: ans_ssh-rh-adabsentuser.group
    dest: /etc/ssh/matches-available/ans_ssh-rh-adabsentuser.group
    owner: root
    group: root
    mode: '0600'

- name: copied adabsent suders file
  copy:
    src: ans-rh-adabsentsudo
    dest: /etc/sudoers.d/ans-rh-adabsentsudo
    owner: root
    group: root
    mode: '0600'

- name: enabled localtechm ssh group login
  ansible.builtin.file:
    src: /etc/ssh/matches-available/ans_ssh-rh-adabsentadmin.group
    dest: /etc/ssh/matches-enabled/05_ans_ssh-rh-adabsentadmin.group
    owner: root
    group: root
    state: link

- name: enabled local user ssh group login
  ansible.builtin.file:
    src: /etc/ssh/matches-available/ans_ssh-rh-adabsentuser.group
    dest: /etc/ssh/matches-enabled/05_ans_ssh-rh-adabsentuser.group
    owner: root
    group: root
    state: link

- name: Added redhat local sudo group
  ansible.builtin.group:
    name: adabsentsudo
    state: present

- name: Added redhat local admin login group
  ansible.builtin.group:
    name: adabsentadmin
    state: present

- name: Added redhat local user login group
  ansible.builtin.group:
    name: adabsentuser
    state: present

- name: Added redhat installer user
  ansible.builtin.user:
    name: "{{ localuser }}"
    uid: 20010
    group: adabsentadmin
    groups: adabsentsudo
    comment: "local user as server doesn't have AD auth"
    update_password: on_create
    password: "{{ localpassword|password_hash('sha512') }}"

- name: reload sshd
  shell: /usr/local/sbin/apply_ssh.sh
