#learn what packages are installed
- name: Make sure splunk server package is not installed
  package_facts:
    manager: auto

#learn if splunk binary exists
- name: Check if the splunk binary exists
  stat:
    path: /opt/splunkforwarder/bin/splunk
  register: splunk_file_check_result


- name: Stop the splunk service
  command: /bin/systemctl stop splunk.service
  when:
   - splunk_file_check_result.stat.exists == True

#when the package "splunk" is not installed and the os is debian based
- name: Install the latest splunkforwarder package
  apt:
    deb: https://odin.snap.net.nz/3rdparty-packages/splunkforwarder_latest.deb
  ignore_errors: yes
  when: ansible_facts['distribution'] == 'Ubuntu'

- name: copy splunk rmp to remote computer
  copy:
   src: installers/splunkforwarder-7.3.0-657388c7a488-linux-2.6-x86_64.rpm
   dest: /tmp/splunkforwarder-7.3.0-657388c7a488-linux-2.6-x86_64.rpm
  ignore_errors: yes
  when: ansible_facts['distribution'] == 'CentOS' or ansible_facts['distribution'] == 'RedHat'

- name: Install the latest splunkforwarder package
  yum:
    name: /tmp/splunkforwarder-7.3.0-657388c7a488-linux-2.6-x86_64.rpm
    state: present
  ignore_errors: yes
  when: ansible_facts['distribution'] == 'CentOS' or ansible_facts['distribution'] == 'RedHat'

- name: Re-Accept the splunk licence
  command: /opt/splunkforwarder/bin/splunk enable boot-start --accept-license --answer-yes --no-prompt -user splunk
  when:
   - splunk_file_check_result.stat.exists == True

- name: Start the splunk service
  command: /bin/systemctl start splunk.service
  when:
   - splunk_file_check_result.stat.exists == True
