---
# tasks file for deploy_splunkforwarder
#learn what packages are installed
- name: Make sure splunk server package is not installed
  package_facts:
    manager: auto

- name: install extra software
  import_tasks: extra_software.yml

- name: run splunk install tasks
  import_tasks: install_splunkforwarder.yml
  when:
    - "'splunkforwarder' not in ansible_facts.packages"

- name: run 2d-splunkforwarder install tasks
  import_tasks: install_2d-splunkforwarder.yml
  ignore_errors: yes
  when: ansible_facts['distribution'] == 'Ubuntu'

- name: deploy configs
  import_tasks: configure_splunk.yml

- name: splunk user
  import_tasks: configure_user.yml

- name: update firewall
  import_tasks: configure_firewall.yml

- name: enable splunk
  import_tasks: enable_splunk.yml

#- name: configure selinux
#  import_tasks: configure_selinux.yml
