###########################
#########cleanup###########
###########################
- hosts: newservers
  gather_facts: false

  vars:
    - ansible_python_interpreter: /usr/bin/python3

  vars_files:
    - "../vars/newserver_vcenterdetails.yml"
    - "../tmp/{{inventory_hostname}}.yml"

  roles:
    - newserver_cleanup
