###########################
#########cleanup###########
###########################
- hosts: newservers
  gather_facts: false
#  serial: 3

  vars:
    - ansible_python_interpreter: /usr/bin/python3

  vars_files:
    - "../tmp/{{inventory_hostname}}.yml"

  roles:
    - newserver_cleanup
