######################################
###########deploy template############
######################################
- hosts: newservers
  gather_facts: false
  serial: 1

  vars_prompt:
    - name: vcenter_username
      prompt: "please enter your vcenter username"
      private: no
    - name: vcenter_password
      prompt: "please enter your password"
      private: yes

  vars:
    - ansible_python_interpreter: /usr/bin/python3

  vars_files:
    - "../vars/newserver_vcenterdetails.yml"
    - "../tmp/{{inventory_hostname}}.yml"
    - "../vars/newserver_ca_passphrase.yml"

  roles:
    - newserver_vm_from_template
    - newserver_access

- hosts: gary
  gather_facts: false
  become: yes
  become_method: sudo

#  vars_files:
#    - "../tmp/{{inventory_hostname}}.yml"

  tasks:
##put the copy clients.d files to gary stuff here
    - name: get uptime
      shell: /usr/bin/uptime
      changed_when: False
      register: uptime

    - debug: var={{ item }}
      with_items:
        - uptime.stdout

##copy files to gary
    - name: copy ipv4 clients files to gary
      ansible.builtin.copy:
        src: ../tmp/radius/
        dest: /tmp
        owner: root
        group: freerad
        mode: '0640'

#    - name: copy ipv6 clients files to gary
#      ansible.builtin.copy:
#        src: tmp/{{ vm_ipv6_address_underscores }}
#        dest: /tmp/{{ vm_ipv6_address_underscores }}
#        owner: root
#        group: freerad
#        mode: '0640'
