###################################
#######configure the server########
###################################

- hosts: newservers
  remote_user: zeus
  become: yes
  become_method: sudo
  gather_facts: false
  serial: 2
  vars:
    - ansible_ssh_private_key_file: "./tmp/ansible-deploy.key"
    - ansible_python_interpreter: /usr/bin/python3

  vars_files:
    - "../tmp/{{inventory_hostname}}.yml"

  tasks:
  - name: make sure the server is up and running, Wait 30 seconds, but only start checking after 30 seconds
    wait_for_connection:
      delay: 20
      timeout: 300

