######################################
###########deploy template############
######################################
- hosts: singleserver
  gather_facts: true
#  serial: 3

  vars:
    - ansible_python_interpreter: /usr/bin/python3

#  vars_files:
#    - "../tmp/{{inventory_hostname}}.yml"
#    - "../vars/newserver_ca_passphrase.yml"

  roles:
    - vm_new_disk_test
#    - newserver_vm_from_template
#    - newserver_vm_reboot
#    - newserver_access
