- name: base server setup
  hosts: newserver
  remote_user: zeus
  become: yes
  become_method: sudo
  gather_facts: true
  ignore_unreachable: true
  #how many to run at once
  serial: 4

  roles:
    - base_role
