
#- hosts: localhost
#  gather_facts: false

#- name: Include only files matching yaml or yml
#  vars_files:
#      - 'vars_disks/{{ ansible_play_batch }}.yaml'
#      - 'vars_disks/{{ ansible_play_batch }}.yml'

- name: vcenter new disk
  import_playbook: b-disk-create.yml

#- name: parted
#  import_playbook: b-mount.yml
