- name: install 2d-ssh
  hosts: singleserver
  become: yes
  become_method: sudo
  ignore_unreachable: true
  #how many to run at once
  vars:
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - install_commvault
