#how to run this playbook
#ansible-playbook playbooks/install_2dradiusauth.yml --ask-vault-pass
- name: install 2d-radiusauth
  hosts: newserver
  remote_user: zeus
  become: yes
  become_method: sudo
  ignore_unreachable: true
  #how many to run at once
  gather_facts: true
  serial: 1
  vars:
    - ansible_python_interpreter: /usr/bin/python3
  vars_files:
    - "../vars/newserver_ubuntu18.yml"
    - "../vars/newserver_ca_passphrase.yml"

  roles:
    - install_2dradiusauth
