- name: Install splunkforwarder on ubuntu 16.04 servers and newer
  hosts: newserver
  remote_user: zeus
  become: yes
  become_method: sudo
  gather_facts: true
  ignore_unreachable: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  #how many to run at once
  serial:
  - 1
  - 2
  - 5
  roles:
    - install_branding
