#https://docs.ansible.com/ansible/latest/modules/copy_module.html
#how to run this playbook
#required pacakges pip3 install --user pyvmomi pyvim
#ansible-playbook playbooks/deploy_signed_cert.yml --ask-vault-pass

#looping over files

#https://docs.ansible.com/ansible/2.4/playbooks_loops.html#looping-over-files

######################################
###########deploy template############
######################################
- hosts: localhost
  gather_facts: false

  vars_prompt:
    - name: vcenter_username
      prompt: "please enter your vcenter username"
      private: no
    - name: vcenter_password
      prompt: "please enter your password"
      private: yes

  vars:
    - ansible_python_interpreter: /usr/bin/python3

  vars_files:
    - "../vars/newserver_vcenterdetails.yml"
    - "../vars/newserver_ubuntu18.yml"
    - "../vars/newserver_ca_passphrase.yml"

  roles:
    - newserver_vm_from_template

  tasks:
  - name: generate the radius secret
    command: /usr/bin/pwgen -s -B 16 1
    register: radius_secret

  - name: remove ssh_host_ed25519_key.pub from ansilbe server now
    file:
      path: ../files/ssh_host_ed25519_key.pub
      state: absent

  - name: remove ssh_host_ed25519_key-cert.pub from ansilbe server now
    file:
      path: ../files/ssh_host_ed25519_key-cert.pub
      state: absent

  - name: remove ssh_host_ed25519_key from ansilbe server now
    file:
      path: ../files/ssh_host_ed25519_key
      state: absent

  - name: generate a server host key
    command: /usr/bin/ssh-keygen -t ed25519 -N "" -f ../files/ssh_host_ed25519_key

  - name: sign the hostkey
    command: /usr/bin/ssh-keygen -s ../files/server_ca -I 2degrees-server_{{ vm_shortname }} -h -n {{ vm_shortname }}.snap.net.nz,{{ vm_shortname }}.2degrees.nz,{{ vm_shortname }}.2dl.nz,{{ vm_shortname }}.nzc.co.nz -P {{ ca_passphrase }} -V +300w ../files/ssh_host_ed25519_key.pub

  - name: Add host to group deployedserver
    add_host:
     name: '{{ vm_fqdn }}'
     groups: deployedserver
     ansible_ssh_private_key_file: './files/ansible-deploy.key'
     ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'

###################################
#######configure the server########
###################################

- hosts: deployedserver
  remote_user: zeus
  become: yes
  become_method: sudo
  gather_facts: true
  vars:
    - ansible_ssh_private_key_file: "./files/ansible-deploy.key"
    - ansible_python_interpreter: /usr/bin/python3

  vars_files:
    - "../vars/newserver_vcenterdetails.yml"
    - "../vars/newserver_ubuntu18.yml"

  roles:
#place signed host_keys onto the server
    - configure_hostcerts
#setup base connectivity
    - newserver_networking
#configures the hostname of the server
    - configure_hostname
#cleans up the server so clones of templates become indipendant from each other
    - clean_serverscript
#configures the repositories that the OS uses to get updates and software
    - configure_repos
#sets up loging on the servers
    - install_2dlogging
#make sure server can reach it's set repository
    - base_role
#deployes required 2degrees certificates onto the servers
    - deploy_certs
#setups 2degrees standard firewall
    - install_2d-firewall
#configures the servers to allow them to email out if need be
    - install_email
#install and configure auditd for auditing purposes
    - install_auditd
#install linux virus scanner
    - install_clamav
#configures the home folder to 2degrees standards
    - install_2dhome
#configures the server to use radius for AD authentication
    - install_2dradiusauth
#configures ssh to 2degrees hardened standard
    - install_2dssh
#sets up ntp on the server
    - install_ntp
#sets up splunk forwarder to send logs to splunk forwarder
    - install_splunkforwarder
#configures the login messages to TASS/PCI/SOX standards
    - install_branding
#installs usefull sysadmin tools
    - install_2dutils
#installs rootkit detection
    - install_rkhunter
#configurs snmpd to allow thigns to send traps to zenoss
    - install_2dsnmpd
#setups zenoss user for zenoss management
    - install_zenoss
#Hardens ubuntu to level2 compliance
    - harden_ub18
#setups breakglass utils/permissions
    - configure_bgaccounts
#grants sudo permissions to sysadmin security group
    - permissions_sudo-sysadmin
#grants sudo permissions to techm security group
    - permissions_sudo-techm
#install aide late so we don't have heaps of changes for the next scan because we are setting up the os
    - install_2daide
#Auto updates come at the end so it doens't start updating while we are setting up the vm
    - install_autoupdates
#run the postinstall cleanup role
    - postinstall_cleanup

###########################
#########cleanup###########
###########################
- hosts: localhost
  gather_facts: false

  vars:
    - ansible_python_interpreter: /usr/bin/python3

  vars_files:
    - "../vars/newserver_vcenterdetails.yml"
    - "../vars/newserver_ubuntu18.yml"

  tasks:
  - name: remove ssh_host_ed25519_key.pub from ansilbe server now
    file:
      path: ../files/ssh_host_ed25519_key.pub
      state: absent

  - name: remove ssh_host_ed25519_key-cert.pub from ansilbe server now
    file:
      path: ../files/ssh_host_ed25519_key-cert.pub
      state: absent

  - name: remove ssh_host_ed25519_key from ansilbe server now
    file:
      path: ../files/ssh_host_ed25519_key
      state: absent

#  - name: reboot the vm using vmware guest
#    community.vmware.vmware_guest_powerstate:
#      hostname: "{{ vcenter_hostname }}"
#      username: "{{ vcenter_username }}"
#      password: "{{ vcenter_password }}"
#      name: "{{ vm_hostname }}"
#      validate_certs: no
#      folder: "/{{ vcenter_datacenter }}/{{ vcenter_folder }}"
#      state: reboot-guest
#    delegate_to: localhost
