- name:
  hosts: netbox_platform_server-ubuntu-14:netbox_platform_server-ubuntu-16
  gather_facts: true
  ignore_unreachable: true
  #how many to run at once
  serial: 4

  tasks:

  - debug:
      msg: System "{{ inventory_hostname }}" has gateway "{{ ansible_default_ipv4.gateway }}"
