- name: enable sysadmin
  ansible.builtin.file:
    src: /etc/ssh/matches-available/ans_ipa.conf
    dest: /etc/ssh/matches-enabled/05_ans_ipa.conf
    owner: root
    group: root
    state: link

#- name: enable sysadmin
#  ansible.builtin.file:
#    src: /etc/ssh/matches-available/ans_zeus.user
#    dest: /etc/ssh/matches-enabled/05_ans_zeus.user
#    owner: root
#    group: root
#    state: link
