##################################
#######grub audit options#########
##################################

- name: set grub audit=1 and audit_backlog_limit=10000 if it doesn't exist
  lineinfile:
    path: /etc/default/grub
    state: present
    regex: '^(GRUB_CMDLINE_LINUX=\")(?:(audit_backlog_limit=10000 audit=1 ))?(.*\"$)'
    line: '\1audit_backlog_limit=11000 audit=1 \3'
    backrefs: yes

- name: update grub on centos
  shell: /usr/sbin/grub2-mkconfig -o /boot/grub2/grub.cfg
  ignore_errors: yes
  when: ansible_facts['distribution'] == 'CentOS' or ansible_facts['distribution'] == 'RedHat'

- name: update grub on ubuntu
  shell: /usr/sbin/update-grub
  ignore_errors: yes
  when: ansible_facts['distribution'] == 'Ubuntu'

- name: enable audit rules redhat
  shell: /usr/sbin/augenrules --load
  when: ansible_facts['distribution'] == 'CentOS' or ansible_facts['distribution'] == 'RedHat'

- name: enable audit rules ubuntu
  shell: /sbin/augenrules --load
  when: ansible_facts['distribution'] == 'Ubuntu'
