- name: Ubuntu Check repo https://odin.snap.net.nz is accessable
  uri:
    url: https://odin.snap.net.nz
    timeout: 10
  ignore_errors: yes
  when: ansible_facts['distribution'] == 'Ubuntu'

#- name: Redhat satellite check repo https://snzclakl173.nzc.co.nz is accessable
#  uri:
#    url: https://snzclakl173.nzc.co.nz/XMLRPC
#    url: https://snzclakl173.nzc.co.nz
#   timeout: 10
#   validate_certs: no
#  ignore_errors: yes
#  when: ansible_facts['distribution'] == 'RedHat'
