---
# tasks file for configure_hostname


- name: Set up a unique hostname
  hostname: name={{ vm_shortname }}

- name: Add the server's domain to the hosts file ipv4
  lineinfile:
    dest: /etc/hosts
    regexp: '^(127\.0\.0\.1).*(localhost.*)'
    line: '\1 {{ vm_shortname }}.{{ vm_domain }} {{ vm_shortname }} \2'
    state: present
    backrefs: true

- name: Add the server's domain to the hosts file ipv6
  lineinfile:
    dest: /etc/hosts
    regexp: '^(::1).*(localhost .*)'
    line: '\1 {{ vm_shortname }}.{{ vm_domain }} {{ vm_shortname }} \2'
    state: present
    backrefs: true

#make sure we don't have a pretty name, as we dont need it
- name: Remove /etc/machine-info (delete file) as we don't need a pretty name
  ansible.builtin.file:
    path: /etc/machine-info
    state: absent
