---
# tasks file for configure_hostname


- name: Set up a unique hostname
  hostname: name={{ new_hostname }}.2dl.nz

- name: Add the server's domain to the hosts file ipv4
  lineinfile:
    dest: /etc/hosts
    regexp: '^(127\.0\.0\.1).*(localhost.*)'
    line: '\1 {{ new_hostname }}.2dl.nz {{ new_hostname}} \2'
    state: present
    backrefs: true

- name: Add the server's domain to the hosts file ipv6
  lineinfile:
    dest: /etc/hosts
    regexp: '^(::1).*(localhost .*)'
    line: '\1 {{ new_hostname }}.2dl.nz {{ new_hostname}} \2'
    state: present
    backrefs: true

